FROM node:21-alpine as builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:21-alpine as runner
WORKDIR /app
COPY --from=builder /app/ ./
EXPOSE 3000
ENTRYPOINT ["npm", "start"]
